language: generic

#Tell Travis super user pemissions are needed
sudo: required

#Tell Travis what services are needed
services:
  - docker

#Tell Travis what to run before build
before_install:
  - docker build -t jeevakalaiselvam/docker-cicd-react-github-travis-aws -f Dockerfile.dev .

#Tell travel how to run the test for react application
script:
  - docker run -e CI=true jeevakalaiselvam/docker-cicd-react-github-travis-aws npm run test

